name: 'Tests: node.js `assert`'

on: [pull_request, push]

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      requireds: ${{ steps.set-matrix.outputs.requireds }}
      optionals: ${{ steps.set-matrix.outputs.optionals }}
    steps:
      - uses: ljharb/actions/node/matrix@main
        id: set-matrix
        with:
          type: 'majors'
          requireds: '^12.16 || >= 13.4'
          optionals: '>= 8 < 12.16 || ^13.0 < 13.4'

  assert-required:
    needs: [matrix]
    name: 'assert: required'
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.matrix.outputs.requireds) }}

    steps:
      - uses: actions/checkout@v2
      - uses: ljharb/actions/node/install@main
        name: 'nvm install ${{ matrix.node-version }} && npm install'
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm run tests-only
        env:
          ASSERT: true
      - uses: codecov/codecov-action@v2

  assert-optional:
    needs: [matrix]
    name: 'assert: optional'
    runs-on: ubuntu-latest
    continue-on-error: true

    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.matrix.outputs.optionals) }}

    steps:
      - uses: actions/checkout@v2
      - uses: ljharb/actions/node/install@main
        name: 'nvm install ${{ matrix.node-version }} && npm install'
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm run tests-only
        env:
          ASSERT: true
      - uses: codecov/codecov-action@v2

  assert:
    name: 'node: assert'
    needs: [assert-required, assert-optional]
    runs-on: ubuntu-latest
    steps:
      - run: 'echo tests completed'
